# Generated by Django 4.2 on 2023-04-26 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0004_article_dislike"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="when",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
