# Generated by Django 4.2 on 2023-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0006_remove_article_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created_when",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
